name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug here..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "What should happen..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "What actually happened..."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component does this bug affect?
      options:
        - home-mixer (Rust service)
        - phoenix (ML models)
        - thunder (in-memory store)
        - candidate-pipeline (framework)
        - scripts (deployment)
        - documentation
        - other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: "e.g., v1.0.0, main branch, etc."

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
        - OS: (e.g., macOS 12.0, Ubuntu 20.04)
        - Rust version: (run `rustc --version`)
        - Python version: (run `python --version`)
        - Any other relevant environment details
      placeholder: |
        - OS: Ubuntu 20.04
        - Rust: rustc 1.70.0
        - Python: Python 3.9.0

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Any additional information, logs, screenshots, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched for existing issues to avoid duplicates
          required: true
        - label: I have included all relevant information
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/mangeshraut712/x-algorithm/blob/main/docs/CONTRIBUTING.md)
          required: true
